### ISSUE TITLE
BUG:Crash while project version have no build number

### ISSUE THREAD

**Issue by LaysDragon** [arononak/git_stamp#1]
In my case,build number only existed in ci/cd env,so in local dev only come with version with no build number,which cause follow command crash.
`dart run git_stamp --gen-only app-version,app-build`
I think it return some default value like 0 while build number list are empty.
```
Building package executable... 
Built git_stamp:git_stamp.


    ┏┓•   ┏┓          ┏┓
    ┃┓┓╋  ┗┓╋┏┓┏┳┓┏┓  ┃┓┏┓┏┓┏┓┏┓┏┓╋┏┓┏┓
    ┗┛┗┗  ┗┛┗┗┻┛┗┗┣┛  ┗┛┗ ┛┗┗ ┛ ┗┻┗┗┛┛
                  ┛



GitStamp 4.2.0

Build Type: custom ([app-version, app-build])

INFO:   Generated - 450.00 B     lib/git_stamp/git_stamp.dart
INFO:   Generated - 47.00 B      lib/git_stamp/git_stamp_tool_version.dart
INFO:   Generated - 46.00 B      lib/git_stamp/src/data/app_version.dart
Unhandled exception:
Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      AppBuild.content (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/git_stamp-4.2.0/bin/src/files/dynamic/git_stamp_dynamic_files.dart:236:49)
#2      GitStampFile.generate (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/git_stamp-4.2.0/bin/src/git_stamp_file.dart:24:40)
#4      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/git_stamp-4.2.0/bin/git_stamp.dart:107:9)
<asynchronous suspension>
```

**Comment by arononak** [comment]
@LaysDragon Thank you for your trust and for writing about the bug.

https://github.com/arononak/git_stamp/commit/30d272e143d2440dcfe0e5e1ed4549e7695f683a
I fixed it and it will be in the release on Wednesday 14.08.2024. I release new versions every 7 days. If you want to use it now, you can do it by directly downloading the package from GitHub instead of pub.dev:
```yml
dev_dependencies:
  git_stamp:
    git:
      url: https://github.com/arononak/git_stamp.git
      ref: main
```

Thanks !
